In [1]:
import pandas as pd

In [2]:
filename = 'KaggleV2-May-2016_with_new_cols_may5_1338.csv'
no_show = pd.read_csv(filename, encoding='latin')

In [4]:
weather_dailysummary = 'weather_dailysummary.csv'
weather = pd.read_csv(weather_dailysummary)

In [5]:
weather.head()

,minpressurem,minhumidity,maxtempi,mintempi,maxpressurei,precipm,mindewptm,meanwindspdm,meandewpti,mintempm,...,maxwspdm,maxdewptm,meantempi,date_tzname,date_mon,date_hour,date_min,date_year,date_pretty,date_mday
0,1015.1,77,74.1,70.9,30.09,0.3,18.0,14.7,66.2,21.6,...,38.6,20.3,72.5,America/Sao_Paulo,4,0,0,2016,"April 29, 2016",29
1,1012.8,75,79.1,69.1,30.02,0.0,18.8,8.1,68.8,20.6,...,30.6,21.8,74.1,America/Sao_Paulo,4,0,0,2016,"April 30, 2016",30
2,1015.5,63,75.1,68.8,30.17,3.0,15.3,21.4,63.3,20.4,...,38.6,19.2,71.9,America/Sao_Paulo,5,0,0,2016,"May 1, 2016",1
3,1019.5,51,78.5,68.4,30.21,0.0,10.2,13.7,59.2,20.2,...,29.0,18.1,73.4,America/Sao_Paulo,5,0,0,2016,"May 2, 2016",2
4,1018.8,69,77.5,65.5,30.19,0.0,16.4,6.5,66.2,18.6,...,20.9,20.8,71.5,America/Sao_Paulo,5,0,0,2016,"May 3, 2016",3

In [18]:

weather['AppointmentDay'] = pd.to_datetime(weather['date_pretty'])

In [19]:
weather.head()

,minpressurem,minhumidity,maxtempi,mintempi,maxpressurei,precipm,mindewptm,meanwindspdm,meandewpti,mintempm,...,meantempi,date_tzname,date_mon,date_hour,date_min,date_year,date_pretty,date_mday,datetime,AppointmentDay
0,1015.1,77,74.1,70.9,30.09,0.3,18.0,14.7,66.2,21.6,...,72.5,America/Sao_Paulo,4,0,0,2016,"April 29, 2016",29,2016-04-29,2016-04-29
1,1012.8,75,79.1,69.1,30.02,0.0,18.8,8.1,68.8,20.6,...,74.1,America/Sao_Paulo,4,0,0,2016,"April 30, 2016",30,2016-04-30,2016-04-30
2,1015.5,63,75.1,68.8,30.17,3.0,15.3,21.4,63.3,20.4,...,71.9,America/Sao_Paulo,5,0,0,2016,"May 1, 2016",1,2016-05-01,2016-05-01
3,1019.5,51,78.5,68.4,30.21,0.0,10.2,13.7,59.2,20.2,...,73.4,America/Sao_Paulo,5,0,0,2016,"May 2, 2016",2,2016-05-02,2016-05-02
4,1018.8,69,77.5,65.5,30.19,0.0,16.4,6.5,66.2,18.6,...,71.5,America/Sao_Paulo,5,0,0,2016,"May 3, 2016",3,2016-05-03,2016-05-03

In [15]:
no_show.AppointmentDay = pd.to_datetime(no_show['AppointmentDay'])

In [16]:
no_show.dtypes

PatientId                        float64
AppointmentID                      int64
Gender                            object
ScheduledDay                      object
AppointmentDay            datetime64[ns]
Age                                int64
Neighbourhood                     object
Scholarship                        int64
Hipertension                       int64
Diabetes                           int64
Alcoholism                         int64
Handcap                            int64
SMS_received                       int64
No-show                           object
time_d                            object
time_d_total_seconds             float64
a_day_of_week                      int64
s_day_of_week                      int64
Neighbourhood_category             int64
Gender_category                    int64
no_show                             bool
scheduled_hour                     int64
time_d_total_days                  int64
dtype: object

In [17]:
no_show.head()

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,...,No-show,time_d,time_d_total_seconds,a_day_of_week,s_day_of_week,Neighbourhood_category,Gender_category,no_show,scheduled_hour,time_d_total_days
0,2.987250e+13,5642903,F,2016-04-29 18:38:08,2016-04-29,62,JARDIM DA PENHA,0,1,0,...,No,-1 days +05:21:52.000000000,-67088.0,4,4,39,0,False,18,0
1,5.589980e+14,5642503,M,2016-04-29 16:08:27,2016-04-29,56,JARDIM DA PENHA,0,0,0,...,No,-1 days +07:51:33.000000000,-58107.0,4,4,39,1,False,16,0
2,4.262960e+12,5642549,F,2016-04-29 16:19:04,2016-04-29,62,MATA DA PRAIA,0,0,0,...,No,-1 days +07:40:56.000000000,-58744.0,4,4,45,0,False,16,0
3,8.679510e+11,5642828,F,2016-04-29 17:29:31,2016-04-29,8,PONTAL DE CAMBURI,0,0,0,...,No,-1 days +06:30:29.000000000,-62971.0,4,4,54,0,False,17,0
4,8.841190e+12,5642494,F,2016-04-29 16:07:23,2016-04-29,56,JARDIM DA PENHA,0,1,1,...,No,-1 days +07:52:37.000000000,-58043.0,4,4,39,0,False,16,0

In [37]:
result = pd.merge(no_show, weather, how='left', on='AppointmentDay')

In [38]:
pd.set_option("display.max_columns",101)

In [39]:
result.head()

,PatientId,AppointmentID,Gender,ScheduledDay,AppointmentDay,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received,No-show,time_d,time_d_total_seconds,a_day_of_week,s_day_of_week,Neighbourhood_category,Gender_category,no_show,scheduled_hour,time_d_total_days,minpressurem,minhumidity,maxtempi,mintempi,maxpressurei,precipm,mindewptm,meanwindspdm,meandewpti,mintempm,maxhumidity,maxpressurem,meantempm,precipi,meanwdire,maxwspdi,humidity,minpressurei,maxdewpti,maxtempm,mindewpti,meandewptm,meanwindspdi,meanwdird,maxwspdm,maxdewptm,meantempi,date_tzname,date_mon,date_hour,date_min,date_year,date_pretty,date_mday,datetime
0,2.987250e+13,5642903,F,2016-04-29 18:38:08,2016-04-29,62,JARDIM DA PENHA,0,1,0,0,0,0,No,-1 days +05:21:52.000000000,-67088.0,4,4,39,0,False,18,0,1015.1,77.0,74.1,70.9,30.09,0.3,18.0,14.7,66.2,21.6,87.0,1018.8,22.5,0.01,SSW,24.0,81.0,29.98,68.5,23.4,64.4,19.0,9.1,NaN,38.6,20.3,72.5,America/Sao_Paulo,4.0,0.0,0.0,2016.0,"April 29, 2016",29.0,2016-04-29
1,5.589980e+14,5642503,M,2016-04-29 16:08:27,2016-04-29,56,JARDIM DA PENHA,0,0,0,0,0,0,No,-1 days +07:51:33.000000000,-58107.0,4,4,39,1,False,16,0,1015.1,77.0,74.1,70.9,30.09,0.3,18.0,14.7,66.2,21.6,87.0,1018.8,22.5,0.01,SSW,24.0,81.0,29.98,68.5,23.4,64.4,19.0,9.1,NaN,38.6,20.3,72.5,America/Sao_Paulo,4.0,0.0,0.0,2016.0,"April 29, 2016",29.0,2016-04-29
2,4.262960e+12,5642549,F,2016-04-29 16:19:04,2016-04-29,62,MATA DA PRAIA,0,0,0,0,0,0,No,-1 days +07:40:56.000000000,-58744.0,4,4,45,0,False,16,0,1015.1,77.0,74.1,70.9,30.09,0.3,18.0,14.7,66.2,21.6,87.0,1018.8,22.5,0.01,SSW,24.0,81.0,29.98,68.5,23.4,64.4,19.0,9.1,NaN,38.6,20.3,72.5,America/Sao_Paulo,4.0,0.0,0.0,2016.0,"April 29, 2016",29.0,2016-04-29
3,8.679510e+11,5642828,F,2016-04-29 17:29:31,2016-04-29,8,PONTAL DE CAMBURI,0,0,0,0,0,0,No,-1 days +06:30:29.000000000,-62971.0,4,4,54,0,False,17,0,1015.1,77.0,74.1,70.9,30.09,0.3,18.0,14.7,66.2,21.6,87.0,1018.8,22.5,0.01,SSW,24.0,81.0,29.98,68.5,23.4,64.4,19.0,9.1,NaN,38.6,20.3,72.5,America/Sao_Paulo,4.0,0.0,0.0,2016.0,"April 29, 2016",29.0,2016-04-29
4,8.841190e+12,5642494,F,2016-04-29 16:07:23,2016-04-29,56,JARDIM DA PENHA,0,1,1,0,0,0,No,-1 days +07:52:37.000000000,-58043.0,4,4,39,0,False,16,0,1015.1,77.0,74.1,70.9,30.09,0.3,18.0,14.7,66.2,21.6,87.0,1018.8,22.5,0.01,SSW,24.0,81.0,29.98,68.5,23.4,64.4,19.0,9.1,NaN,38.6,20.3,72.5,America/Sao_Paulo,4.0,0.0,0.0,2016.0,"April 29, 2016",29.0,2016-04-29

In [61]:
no_show[no_show['AppointmentDay'] > pd.to_datetime('20160608', format='%Y%m%d', errors='ignore')]

Empty DataFrame
Columns: [PatientId, AppointmentID, Gender, ScheduledDay, AppointmentDay, Age, Neighbourhood, Scholarship, Hipertension, Diabetes, Alcoholism, Handcap, SMS_received, No-show, time_d, time_d_total_seconds, a_day_of_week, s_day_of_week, Neighbourhood_category, Gender_category, no_show, scheduled_hour, time_d_total_days]
Index: []

In [40]:
result.groupby('AppointmentDay').count()

,PatientId,AppointmentID,Gender,ScheduledDay,Age,Neighbourhood,Scholarship,Hipertension,Diabetes,Alcoholism,Handcap,SMS_received,No-show,time_d,time_d_total_seconds,a_day_of_week,s_day_of_week,Neighbourhood_category,Gender_category,no_show,scheduled_hour,time_d_total_days,minpressurem,minhumidity,maxtempi,mintempi,maxpressurei,precipm,mindewptm,meanwindspdm,meandewpti,mintempm,maxhumidity,maxpressurem,meantempm,precipi,meanwdire,maxwspdi,humidity,minpressurei,maxdewpti,maxtempm,mindewpti,meandewptm,meanwindspdi,meanwdird,maxwspdm,maxdewptm,meantempi,date_tzname,date_mon,date_hour,date_min,date_year,date_pretty,date_mday,datetime
AppointmentDay,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2016-04-29,3235,3235,3235,3235,3235,3235,3235,3235,3235,3235,3235,3235,3235,3235,3235,3235,3235,3235,3235,3235,3235,3235,3235,3235,3235,3235,3235,3235,3235,3235,3235,3235,3235,3235,3235,3235,3235,3235,3235,3235,3235,3235,3235,3235,3235,0,3235,3235,3235,3235,3235,3235,3235,3235,3235,3235,3235
2016-05-02,4376,4376,4376,4376,4376,4376,4376,4376,4376,4376,4376,4376,4376,4376,4376,4376,4376,4376,4376,4376,4376,4376,4376,4376,4376,4376,4376,4376,4376,4376,4376,4376,4376,4376,4376,4376,4376,4376,4376,4376,4376,4376,4376,4376,4376,0,4376,4376,4376,4376,4376,4376,4376,4376,4376,4376,4376
2016-05-03,4256,4256,4256,4256,4256,4256,4256,4256,4256,4256,4256,4256,4256,4256,4256,4256,4256,4256,4256,4256,4256,4256,4256,4256,4256,4256,4256,4256,4256,4256,4256,4256,4256,4256,4256,4256,4256,4256,4256,4256,4256,4256,4256,4256,4256,0,4256,4256,4256,4256,4256,4256,4256,4256,4256,4256,4256
2016-05-04,4168,4168,4168,4168,4168,4168,4168,4168,4168,4168,4168,4168,4168,4168,4168,4168,4168,4168,4168,4168,4168,4168,4168,4168,4168,4168,4168,4168,4168,4168,4168,4168,4168,4168,4168,4168,4168,4168,4168,4168,4168,4168,4168,4168,4168,0,4168,4168,4168,4168,4168,4168,4168,4168,4168,4168,4168
2016-05-05,4273,4273,4273,4273,4273,4273,4273,4273,4273,4273,4273,4273,4273,4273,4273,4273,4273,4273,4273,4273,4273,4273,4273,4273,4273,4273,4273,4273,4273,4273,4273,4273,4273,4273,4273,4273,4273,4273,4273,4273,4273,4273,4273,4273,4273,0,4273,4273,4273,4273,4273,4273,4273,4273,4273,4273,4273
2016-05-06,3879,3879,3879,3879,3879,3879,3879,3879,3879,3879,3879,3879,3879,3879,3879,3879,3879,3879,3879,3879,3879,3879,3879,3879,3879,3879,3879,3879,3879,3879,3879,3879,3879,3879,3879,3879,3879,3879,3879,3879,3879,3879,3879,3879,3879,0,3879,3879,3879,3879,3879,3879,3879,3879,3879,3879,3879
2016-05-09,4520,4520,4520,4520,4520,4520,4520,4520,4520,4520,4520,4520,4520,4520,4520,4520,4520,4520,4520,4520,4520,4520,4520,4520,4520,4520,4520,4520,4520,4520,4520,4520,4520,4520,4520,4520,4520,4520,4520,4520,4520,4520,4520,4520,4520,0,4520,4520,4520,4520,4520,4520,4520,4520,4520,4520,4520
2016-05-10,4308,4308,4308,4308,4308,4308,4308,4308,4308,4308,4308,4308,4308,4308,4308,4308,4308,4308,4308,4308,4308,4308,4308,4308,4308,4308,4308,4308,4308,4308,4308,4308,4308,4308,4308,4308,4308,4308,4308,4308,4308,4308,4308,4308,4308,0,4308,4308,4308,4308,4308,4308,4308,4308,4308,4308,4308
2016-05-11,4474,4474,4474,4474,4474,4474,4474,4474,4474,4474,4474,4474,4474,4474,4474,4474,4474,4474,4474,4474,4474,4474,4474,4474,4474,4474,4474,4474,4474,4474,4474,4474,4474,4474,4474,4474,4474,4474,4474,4474,4474,4474,4474,4474,4474,0,4474,4474,4474,4474,4474,4474,4474,4474,4474,4474,4474
2016-05-12,4394,4394,4394,4394,4394,4394,4394,4394,4394,4394,4394,4394,4394,4394,4394,4394,4394,4394,4394,4394,4394,4394,4394,4394,4394,4394,4394,4394,4394,4394,4394,4394,4394,4394,4394,4394,4394,4394,4394,4394,4394,4394,4394,4394,4394,0,4394,4394,4394,4394,4394,4394,4394,4394,4394,4394,4394
2016-05-13,3987,3987,3987,3987,3987,3987,3987,3987,3987,3987,3987,3987,3987,3987,3987,3987,3987,3987,3987,3987,3987,3987,3987,3987,3987,3987,3987,3987,3987,3987,3987,3987,3987,3987,3987,3987,3987,3987,3987,3987,3987,3987,3987,3987,3987,0,3987,3987,3987,3987,3987,3987,3987,3987,3987,3987,3987
2016-05-14,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,39,0,39,39,39,39,39,39,39,39,39,39,39
2016-05-16,4613,4613,4613,4613,4613,4613,4613,4613,4613,4613,4613,4613,4613,4613,4613,4613,4613,4613,4613,4613,4613,4613,4613,4613,4613,4613,4613,4613,4613,4613,4613,4613,4613,4613,4613,4613,4613,4613,4613,4613,4613,4613,4613,4613,4613,0,4613,4613,4613,4613,4613,4613,4613,4613,4613,4613,4613
2016-05-17,4372,4372,4372,4372,4372,4372,4372,4372,4372,4372,4372,4372,4372,4372,4372,4372,4372,4372,4372,4372,4372,4372,4372,4372,4372,4372,4372,4372,4372,4372,4372,4372,4372,4372,4372,4372,4372,4372,4372,4372,4372,4372,4372,4372,4372,0,4372,4372,4372,4372,4372,4372,4372,4372,4372,4372,4372
2016-05-18,4373,4373,4373,4373,4373,4373,4373,4373,4373,4373,4373,4373,4373,4373,4373,4373,4373,4373,4373,4373,4373,4373,4373,4373,4373,4373,4373,4373,4373,4373,4373,4373,4373,4373,4373,4373,4373,4373,4373,4373,4373,4373,4373,4373,4373,0,4373,4373,4373,4373,4373,4373,4373,4373,4373,4373,4373
2016-05-19,4270,4270,4270,4270,4270,4270,4270,4270,4270,4270,4270,4270,4270,4270,4270,4270,4270,4270,4270,4270,4270,4270,4270,4270,4270,4270,4270,4270,4270,4270,4270,4270,4270,4270,4270,4270,4270,4270,4270,4270,4270,4270,4270,4270,4270,0,4270,4270,4270,4270,4270,4270,4270,4270,4270,4270,4270
2016-05-20,3828,3828,3828,3828,3828,3828,3828,3828,3828,3828,3828,3828,3828,3828,3828,3828,3828,3828,3828,3828,3828,3828,3828,3828,3828,3828,3828,3828,3828,3828,3828,3828,3828,3828,3828,3828,3828,3828,3828,3828,3828,3828,3828,3828,3828,0,3828,3828,3828,3828,3828,3828,3828,3828,3828,3828,3828
2016-05-24,4009,4009,4009,4009,4009,4009,4009,4009,4009,4009,4009,4009,4009,4009,4009,4009,4009,4009,4009,4009,4009,4009,4009,4009,4009,4009,4009,4009,4009,4009,4009,4009,4009,4009,4009,4009,4009,4009,4009,4009,4009,4009,4009,4009,4009,0,4009,4009,4009,4009,4009,4009,4009,4009,4009,4009,4009
2016-05-25,3909,3909,3909,3909,3909,3909,3909,3909,3909,3909,3909,3909,3909,3909,3909,3909,3909,3909,3909,3909,3909,3909,3909,3909,3909,3909,3909,3909,3909,3909,3909,3909,3909,3909,3909,3909,3909,3909,3909,3909,3909,3909,3909,3909,3909,0,3909,3909,3909,3909,3909,3909,3909,3909,3909,3909,3909
2016-05-30,4514,4514,4514,4514,4514,4514,4514,4514,4514,4514,4514,4514,4514,4514,4514,4514,4514,4514,4514,4514,4514,4514,4514,4514,4514,4514,4514,4514,4514,4514,4514,4514,4514,4514,4514,4514,4514,4514,4514,4514,4514,4514,4514,4514,4514,0,4514,4514,4514,4514,4514,4514,4514,4514,4514,4514,4514
2016-05-31,4279,4279,4279,4279,4279,4279,4279,4279,4279,4279,4279,4279,4279,4279,4279,4279,4279,4279,4279,4279,4279,4279,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2016-06-01,4464,4464,4464,4464,4464,4464,4464,4464,4464,4464,4464,4464,4464,4464,4464,4464,4464,4464,4464,4464,4464,4464,4464,4464,4464,4464,4464,4464,4464,4464,4464,4464,4464,4464,4464,4464,4464,4464,4464,4464,4464,4464,4464,4464,4464,0,4464,4464,4464,4464,4464,4464,4464,4464,4464,4464,4464
2016-06-02,4310,4310,4310,4310,4310,4310,4310,4310,4310,4310,4310,4310,4310,4310,4310,4310,4310,4310,4310,4310,4310,4310,4310,4310,4310,4310,4310,4310,4310,4310,4310,4310,4310,4310,4310,4310,4310,4310,4310,4310,4310,4310,4310,4310,4310,0,4310,4310,4310,4310,4310,4310,4310,4310,4310,4310,4310
2016-06-03,4090,4090,4090,4090,4090,4090,4090,4090,4090,4090,4090,4090,4090,4090,4090,4090,4090,4090,4090,4090,4090,4090,4090,4090,4090,4090,4090,4090,4090,4090,4090,4090,4090,4090,4090,4090,4090,4090,4090,4090,4090,4090,4090,4090,4090,0,4090,4090,4090,4090,4090,4090,4090,4090,4090,4090,4090
2016-06-06,4692,4692,4692,4692,4692,4692,4692,4692,4692,4692,4692,4692,4692,4692,4692,4692,4692,4692,4692,4692,4692,4692,4692,4692,4692,4692,4692,4692,4692,4692,4692,4692,4692,4692,4692,4692,4692,4692,4692,4692,4692,4692,4692,4692,4692,0,4692,4692,4692,4692,4692,4692,4692,4692,4692,4692,4692
2016-06-07,4416,4416,4416,4416,4416,4416,4416,4416,4416,4416,4416,4416,4416,4416,4416,4416,4416,4416,4416,4416,4416,4416,4416,4416,4416,4416,4416,4416,4416,4416,4416,4416,4416,4416,4416,4416,4416,4416,4416,4416,4416,4416,4416,4416,4416,0,4416,4416,4416,4416,4416,4416,4416,4416,4416,4416,4416
2016-06-08,4479,4479,4479,4479,4479,4479,4479,4479,4479,4479,4479,4479,4479,4479,4479,4479,4479,4479,4479,4479,4479,4479,4479,4479,4479,4479,4479,4479,4479,4479,4479,4479,4479,4479,4479,4479,4479,4479,4479,4479,4479,4479,4479,4479,4479,0,4479,4479,4479,4479,4479,4479,4479,4479,4479,4479,4479

In [66]:
no_show.groupby('AppointmentDay').count().sum()

PatientId                 110527
AppointmentID             110527
Gender                    110527
ScheduledDay              110527
Age                       110527
Neighbourhood             110527
Scholarship               110527
Hipertension              110527
Diabetes                  110527
Alcoholism                110527
Handcap                   110527
SMS_received              110527
No-show                   110527
time_d                    110527
time_d_total_seconds      110527
a_day_of_week             110527
s_day_of_week             110527
Neighbourhood_category    110527
Gender_category           110527
no_show                   110527
scheduled_hour            110527
time_d_total_days         110527
dtype: int64

In [42]:
no_show['AppointmentDay'].count()

110527

In [43]:
result['AppointmentDay'].count()

110527

In [34]:
weather.groupby('AppointmentDay').count()

,minpressurem,minhumidity,maxtempi,mintempi,maxpressurei,precipm,mindewptm,meanwindspdm,meandewpti,mintempm,maxhumidity,maxpressurem,meantempm,precipi,meanwdire,maxwspdi,humidity,minpressurei,maxdewpti,maxtempm,mindewpti,meandewptm,meanwindspdi,meanwdird,maxwspdm,maxdewptm,meantempi,date_tzname,date_mon,date_hour,date_min,date_year,date_pretty,date_mday,datetime
AppointmentDay,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
2016-04-29,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1
2016-04-30,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1
2016-05-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1
2016-05-02,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1
2016-05-03,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1
2016-05-04,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1
2016-05-05,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1
2016-05-06,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1
2016-05-07,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1
2016-05-08,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1
2016-05-09,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1
2016-05-10,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1
2016-05-11,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1
2016-05-12,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1
2016-05-13,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1
2016-05-14,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1
2016-05-15,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1
2016-05-16,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1
2016-05-17,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1
2016-05-18,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1
2016-05-19,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1
2016-05-20,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1
2016-05-21,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1
2016-05-22,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1
2016-05-23,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1
2016-05-24,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1
2016-05-25,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1
2016-05-26,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1
2016-05-27,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1
2016-05-28,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1
2016-05-29,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1
2016-05-30,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1
2016-06-01,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1
2016-06-02,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1
2016-06-03,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1
2016-06-04,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1
2016-06-05,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1
2016-06-06,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1
2016-06-07,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1
2016-06-08,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,1,1,1,1,1,1

In [51]:

#eyeball... sms_recieved has affect on no_show rate

no_show.groupby('AppointmentDay').sum()/no_show.groupby('AppointmentDay').count()

,Age,Alcoholism,AppointmentID,Diabetes,Gender,Gender_category,Handcap,Hipertension,Neighbourhood,Neighbourhood_category,No-show,PatientId,SMS_received,ScheduledDay,Scholarship,a_day_of_week,no_show,s_day_of_week,scheduled_hour,time_d,time_d_total_days,time_d_total_seconds
AppointmentDay,,,,,,,,,,,,,,,,,,,,,,
2016-04-29,35.704482,0.031839,5.594300e+06,0.074498,NaN,0.358578,0.022875,0.190726,NaN,41.966924,NaN,1.465762e+14,0.394127,NaN,0.098918,4.0,0.195672,2.606491,10.800927,NaN,11.094590,9.761711e+05
2016-05-02,36.825640,0.031764,5.611400e+06,0.073583,NaN,0.355804,0.024452,0.207267,NaN,41.611060,NaN,1.453721e+14,0.521938,NaN,0.095064,0.0,0.196755,1.349177,10.651737,NaN,8.964808,7.894900e+05
2016-05-03,37.371006,0.030075,5.618703e+06,0.074013,NaN,0.350094,0.026551,0.208882,NaN,41.317669,NaN,1.467149e+14,0.469220,NaN,0.109962,1.0,0.195254,1.627820,10.700893,NaN,8.322603,7.333602e+05
2016-05-04,36.660509,0.028311,5.623124e+06,0.065499,NaN,0.352447,0.020633,0.202255,NaN,41.357726,NaN,1.394674e+14,0.393954,NaN,0.098369,2.0,0.233445,1.682102,10.788148,NaN,8.212092,7.271785e+05
2016-05-05,37.126141,0.028317,5.627634e+06,0.071144,NaN,0.342850,0.022935,0.204306,NaN,42.288088,NaN,1.415598e+14,0.369998,NaN,0.104610,3.0,0.188860,2.169904,10.832904,NaN,8.299789,7.317582e+05
2016-05-06,37.533643,0.032483,5.630777e+06,0.073473,NaN,0.355762,0.021139,0.195927,NaN,41.435422,NaN,1.504278e+14,0.351637,NaN,0.097190,4.0,0.204950,2.747358,10.606600,NaN,8.718226,7.693171e+05
2016-05-09,37.086726,0.032522,5.639435e+06,0.069027,NaN,0.358186,0.022345,0.198230,NaN,41.600000,NaN,1.472832e+14,0.000000,NaN,0.089159,0.0,0.225442,1.296903,10.772124,NaN,8.902655,7.830712e+05
2016-05-10,36.871634,0.029248,5.646297e+06,0.078923,NaN,0.349350,0.019499,0.198468,NaN,42.371866,NaN,1.486385e+14,0.476323,NaN,0.101207,1.0,0.230269,1.603993,10.880919,NaN,8.285515,7.297340e+05
2016-05-11,36.669200,0.029504,5.648136e+06,0.069513,NaN,0.350693,0.023916,0.187751,NaN,41.328565,NaN,1.445715e+14,0.394949,NaN,0.094546,2.0,0.197810,1.698927,10.775592,NaN,8.880197,7.836866e+05
2016-05-12,36.656122,0.028903,5.653628e+06,0.069640,NaN,0.357988,0.021393,0.197087,NaN,41.670005,NaN,1.451575e+14,0.361629,NaN,0.098316,3.0,0.190487,2.158398,10.914656,NaN,8.627902,7.607406e+05
2016-05-13,36.722598,0.026837,5.656091e+06,0.078004,NaN,0.354402,0.025082,0.203662,NaN,41.454226,NaN,1.483361e+14,0.000000,NaN,0.103837,4.0,0.226988,2.724605,10.707800,NaN,9.152245,8.069447e+05
2016-05-14,53.589744,0.051282,5.680342e+06,0.179487,NaN,0.256410,0.025641,0.487179,NaN,13.102564,NaN,8.001123e+13,0.333333,NaN,0.076923,5.0,0.230769,2.384615,10.564103,NaN,3.435897,3.259552e+05
2016-05-16,36.349881,0.033601,5.663488e+06,0.067852,NaN,0.360936,0.018209,0.188597,NaN,41.082593,NaN,1.530809e+14,0.000000,NaN,0.099935,0.0,0.227401,1.307392,10.785823,NaN,9.692391,8.529514e+05
2016-05-17,36.938472,0.025846,5.672092e+06,0.066560,NaN,0.332342,0.023559,0.185727,NaN,42.164227,NaN,1.497646e+14,0.000000,NaN,0.091720,1.0,0.213861,1.664456,10.931610,NaN,8.726670,7.693772e+05
2016-05-18,36.482049,0.028127,5.674106e+06,0.072490,NaN,0.350332,0.018523,0.191630,NaN,42.021267,NaN,1.479282e+14,0.000000,NaN,0.097645,2.0,0.203522,1.747770,10.713698,NaN,9.277841,8.188939e+05
2016-05-19,36.985480,0.028337,5.678219e+06,0.063700,NaN,0.357611,0.027869,0.194848,NaN,41.098126,NaN,1.475557e+14,0.000000,NaN,0.089227,3.0,0.208899,2.177752,10.827869,NaN,9.414286,8.308297e+05
2016-05-20,36.535789,0.034744,5.681958e+06,0.073929,NaN,0.354754,0.024556,0.179990,NaN,41.897074,NaN,1.496446e+14,0.000000,NaN,0.096134,4.0,0.234848,2.678945,10.947231,NaN,9.741902,8.577154e+05
2016-05-24,37.794712,0.029683,5.697015e+06,0.072088,NaN,0.342230,0.024196,0.202794,NaN,41.909454,NaN,1.474616e+14,0.506361,NaN,0.102519,1.0,0.202295,1.754053,10.852332,NaN,9.135196,8.011257e+05
2016-05-25,37.080327,0.029163,5.698886e+06,0.070606,NaN,0.348427,0.021489,0.189307,NaN,41.990535,NaN,1.508705e+14,0.486825,NaN,0.098746,2.0,0.194167,2.163213,11.090816,NaN,9.900486,8.686202e+05
2016-05-30,37.119849,0.029021,5.699345e+06,0.069783,NaN,0.352681,0.018387,0.192291,NaN,41.629818,NaN,1.466359e+14,0.535224,NaN,0.106779,0.0,0.196721,1.090607,10.877492,NaN,13.283784,1.161824e+06
2016-05-31,37.810937,0.030615,5.707500e+06,0.070110,NaN,0.346109,0.020799,0.207291,NaN,42.121056,NaN,1.493357e+14,0.513905,NaN,0.101426,1.0,0.179247,1.431409,10.998364,NaN,12.367142,1.085038e+06
2016-06-01,38.109991,0.030242,5.719967e+06,0.073925,NaN,0.349238,0.021281,0.197133,NaN,41.568548,NaN,1.475325e+14,0.382841,NaN,0.096998,2.0,0.181900,1.649866,10.612231,NaN,9.969534,8.782201e+05
2016-06-02,38.201160,0.034571,5.726281e+06,0.074478,NaN,0.362877,0.022738,0.208121,NaN,42.618561,NaN,1.455864e+14,0.389095,NaN,0.092343,3.0,0.186079,2.106961,10.616241,NaN,9.513457,8.390057e+05
2016-06-03,38.477995,0.033985,5.727837e+06,0.083863,NaN,0.349633,0.022983,0.213692,NaN,41.311002,NaN,1.500242e+14,0.384108,NaN,0.098533,4.0,0.196822,2.631785,10.523472,NaN,10.412225,9.165157e+05
2016-06-06,36.760017,0.028133,5.738037e+06,0.065857,NaN,0.342072,0.021952,0.180946,NaN,41.527067,NaN,1.514768e+14,0.520887,NaN,0.097613,0.0,0.186061,1.348252,10.573316,NaN,10.118500,8.910009e+05
2016-06-07,36.827219,0.027400,5.745434e+06,0.076993,NaN,0.331748,0.022645,0.198143,NaN,41.456975,NaN,1.462925e+14,0.482337,NaN,0.093071,1.0,0.184783,1.651495,10.735054,NaN,9.432971,8.307737e+05
2016-06-08,37.265238,0.037508,5.748820e+06,0.070775,NaN,0.337575,0.019647,0.200938,NaN,42.711989,NaN,1.481728e+14,0.410583,NaN,0.102255,2.0,0.172806,1.742353,10.670685,NaN,9.601474,8.461334e+05

In [62]:
result_right = pd.merge(no_show, weather, how='inner', on='AppointmentDay')

In [63]:
result_right.count()

PatientId                 106248
AppointmentID             106248
Gender                    106248
ScheduledDay              106248
AppointmentDay            106248
Age                       106248
Neighbourhood             106248
Scholarship               106248
Hipertension              106248
Diabetes                  106248
Alcoholism                106248
Handcap                   106248
SMS_received              106248
No-show                   106248
time_d                    106248
time_d_total_seconds      106248
a_day_of_week             106248
s_day_of_week             106248
Neighbourhood_category    106248
Gender_category           106248
no_show                   106248
scheduled_hour            106248
time_d_total_days         106248
minpressurem              106248
minhumidity               106248
maxtempi                  106248
mintempi                  106248
maxpressurei              106248
precipm                   106248
mindewptm                 106248
meanwindspdm              106248
meandewpti                106248
mintempm                  106248
maxhumidity               106248
maxpressurem              106248
meantempm                 106248
precipi                   106248
meanwdire                 106248
maxwspdi                  106248
humidity                  106248
minpressurei              106248
maxdewpti                 106248
maxtempm                  106248
mindewpti                 106248
meandewptm                106248
meanwindspdi              106248
meanwdird                      0
maxwspdm                  106248
maxdewptm                 106248
meantempi                 106248
date_tzname               106248
date_mon                  106248
date_hour                 106248
date_min                  106248
date_year                 106248
date_pretty               106248
date_mday                 106248
datetime                  106248
dtype: int64

In [67]:
result.to_csv('KaggleV2-May-2016_join_with_weather_may5_1338.csv', index=False)